version: 2.1

executors:
  alpine:
    docker:
      - image: fr3akyphantom/skadoosh:latest

jobs:
  build:
    parameters:
      platform:
        type: string
    executor: alpine
    environment:
      RecName: "MinimalOmniRecovery"
      Link: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git"
      BRANCH: "<< parameters.platform >>"
    steps:
      - checkout
      - run:
          name: "Compression Job for Minimal TWRP with << parameters.platform >> branch"
          command: |
            chmod a+x .circleci/keepalive.sh
            .circleci/keepalive.sh & ./script.sh ${RecName} ${Link} ${BRANCH}
            kill -s SIGTERM $(cat /tmp/keepalive.pid) || true

workflows:
  version: 2
  compress-norepo:
    jobs:
      - build:
          matrix:
            parameters:
              platform: ["twrp-5.1", "twrp-6.0", "twrp-7.1", "twrp-8.1", "twrp-9.0"]
