version: 2.0

jobs:
  "primary": # twrp-8.1
    docker:
      - image: fr3akyphantom/skadoosh:latest
    steps:
      - checkout
      - run:
          name: Run first Parallel job
          command: echo "Running..."; chmod a+x .circleci/act.sh; .circleci/act.sh & ./script.sh $RecName $Link $Branch1

  "secondary": # twrp-7.1
    docker:
      - image: fr3akyphantom/skadoosh:latest
    steps:
      - checkout
      - run:
          name: Run second Parallel job
          command: echo "Running..."; chmod a+x .circleci/act.sh; .circleci/act.sh & ./script.sh $RecName $Link $Branch2

  "third": # twrp-6.0
    docker:
      - image: fr3akyphantom/skadoosh:latest
    steps:
      - checkout
      - run:
          name: Run third Parallel job
          command: echo "Running..."; chmod a+x .circleci/act.sh; .circleci/act.sh & ./script.sh $RecName $Link $Branch3

  "fourth": # twrp-5.1
    docker:
      - image: fr3akyphantom/skadoosh:latest
    steps:
      - checkout
      - run:
          name: Run fourth Parallel job
          command: echo "Running..."; chmod a+x .circleci/act.sh; .circleci/act.sh & ./script.sh $RecName $Link $Branch4

  "fifth": # twrp-9.0
    docker:
      - image: fr3akyphantom/skadoosh:latest
    steps:
      - checkout
      - run:
          name: Run fourth Parallel job
          command: echo "Running..."; chmod a+x .circleci/act.sh; .circleci/act.sh & ./script.sh $RecName $Link $Branch5

workflows:
  version: 2
  build:
    jobs:
      - "primary"     # twrp-8.1
      - "secondary"   # twrp-7.1
      - "third"       # twrp-6.0
      - "fourth"      # twrp-5.1
      - "fifth"       # twrp-9.0
